### ISSUE TITLE
Demo recording that started after a map has started will not play back

### ISSUE THREAD

**Issue by thekovic** [Novum/vkQuake#359]
Any part of a demo that was started after a map has started/restarted will not play back with the playdemo command. Only the messages will be written out into the console. If a demo spans across a map transition or a death, the part of the demo after the transition/death will play back as expected.

Example of demo that doesn't playback right. The demo starts in E1M1, after the map has started. It plays through E1M1 and loads into E1M2 where it ends. Only the few seconds in E1M2 play back however.
[broken_demo.zip](https://github.com/Novum/vkQuake/files/7102529/broken_demo.zip)

**Comment by Novum** [comment]
Is this also buggy in QuakeSpasm-Spiked or a problem that only occurs with vkQuake? Will help narrowing it down.

**Comment by thekovic** [comment]
Quakespasm-Spiked doesn't have this issue. A demo that was started in Quakespasm-Spiked before a map has started/restarted will play back as expected. Note, that only a new demo that was recorded in Quakespasm-Spiked will play back as expected. The broken demo recorded in vkQuake will play back in Quakespasm-Spiked as it did in vkQuake (broken).

**Comment by Novum** [comment]
Thanks

**Comment by AntonSazonov** [comment]
Patch:
File: `cl_demo.c`
Function: `CL_GetDemoMessage`
Replace: `if (fread (&net_message.cursize, 4, 1, cls.demofile) != 4) return 0;`
To: `fread (&net_message.cursize, 4, 1, cls.demofile);`

**Comment by Novum** [comment]
That's not the right way to fix this, but thanks, I'll look st it

**Comment by AntonSazonov** [comment]
Yes. My mistake. `fread` returns number of objects read (3-rd parameter) successfully, so more right solution would be:
`if ( fread( &net_message.cursize, 4, 1, cls.demofile ) != 1 ) return 0;`

**Comment by Novum** [comment]
This was already fixed on Dec 1 9243ee5

**Comment by Ch0wW** [comment]
I've compiled and tested it, but this commit above still doesn't seem to fix the fact a demo recorded midgame isn't playbacked. It only starts at the NEXT map, if there's one.

**Comment by Novum** [comment]
25e45cf224b64a134c9e7b2d2f8cc878519611d8
