### ISSUE TITLE
[Bug] Certain (water) surfaces move depending on camera angle

### ISSUE THREAD

**Issue by Vagankovo** [Novum/vkQuake#391]
## System info
OS - Arch Linux (rolling)
GPU - Radeon RX 5500M & AMD Renoir (integrated graphics)
CPU - Ryzen 7 4800H with Radeon Graphics

vkquake version - 1.11.1

## Bug
Certain water surfaces move depending on your camera angle. I also have seen other surfaces behave like that. This is a graphical glitch.

## Reproduction
HIP1M2 is a good place where this is potentially reproducible.
1. Load HIP1M2
2. Go to an area with water
3. Start looking around in different ways
4. See how the surfaces move.

### Examples in HIP1M2
![Screenshot from 2021-11-13 20-33-18](https://user-images.githubusercontent.com/90520453/141653717-0c68dbd7-a07c-4735-9a89-9d6520034575.png)
![Screenshot from 2021-11-13 20-33-23](https://user-images.githubusercontent.com/90520453/141653720-300989b5-a0e8-4410-b7c0-3d0b3352e4e4.png)
![Screenshot from 2021-11-13 20-34-28](https://user-images.githubusercontent.com/90520453/141653722-09245e13-735f-4b38-b82e-8f7f6d62c1b4.png)

### Example in alk_bdown (mod Alkaline)
![Screenshot from 2021-11-13 20-27-15](https://user-images.githubusercontent.com/90520453/141653789-39e0b04a-0cb4-4822-94e6-0c712d49486e.png)
![Screenshot from 2021-11-13 20-27-21](https://user-images.githubusercontent.com/90520453/141653793-39b8c5a6-1fd3-406d-b122-95aa8558215a.png)

**Comment by Vagankovo** [comment]
Note: I haven't seen this happen in Quakespasm-Spiked

**Comment by Novum** [comment]
This is... extremely weird

**Comment by Vagankovo** [comment]
This seems to be only present when one uses AMDVLK external drivers instead of RADV, the implementation inside the Mesa graphics libraries.
Two possibilities:
1. The code has incompatibility issues with AMDVLK.
2. It's a bug within RADV drivers.

**Comment by Novum** [comment]
Okay, that makes sense because I've never seen this before. Still keeping it open for now, need to check on my AMD machine at some time.

**Comment by Six-Shoota** [comment]
Same happens in windows with drivers ver. 21.12.1. I haven't had the problem with earlier ver.
![vkquake0001](https://user-images.githubusercontent.com/65441436/145669137-e6f99a60-d570-4147-a6a2-7e6744d10641.png)

**Comment by Vagankovo** [comment]
... and AMDVLK drivers share code with AMD's drivers for Windows

**Comment by barneycarroll** [comment]
Came to here to report this. Very odd because I somehow hadn't noticed the phemonenon until the last few days, but it's had debilitating impact on the last 3 maps I've played. I also thought Tears of the False God was a striking example of the bug, lol. It doesn't affect all water brushes, but I can't determine what it is that differentiates the ones that are subject to it and the ones that aren't.

https://user-images.githubusercontent.com/83627/160449873-0001f28e-3d4b-4823-98d2-4580106431fc.mp4

**Comment by barneycarroll** [comment]
Don't know how helpful this is, but I found an incident with adjacent liquid brushes, some of which exhibit the bug and some which don't. In case this is helpful isolating the cause. Map is [Acid Worship](https://www.quaddicted.com/reviews/acidworship_cv.html)

https://user-images.githubusercontent.com/83627/160455282-da1f9873-4ba7-4bcf-8cd4-7ce1b48d1350.mp4

**Comment by Novum** [comment]
Very useful information. I still haven't had time to investigate this, and I still suspect this is a driver issue.

**Comment by notathrowaway2** [comment]
Are  you using the using the latest drivers? I had this issue before but it seems like it was fixed with a recent driver on Windows and Linux.

**Comment by barneycarroll** [comment]
I just upgraded my AMD drivers to latest (22.3.2, from .1) — the issue persists. Vulkan drivers at 2.0.220, Vulkan API 1.3.206.

**Comment by notathrowaway2** [comment]
I just tried an older version of VkQuake(1.12.2) on Windows and the issue still happens with the newest driver. Version 1.13 works fine. On my laptop with Fedora Linux all versions of VkQuake work without issues.

**Comment by Novum** [comment]
Strange that 1.13 works fine

**Comment by barneycarroll** [comment]
Yes — fixed! Sorry I missed the release :)

**Comment by Novum** [comment]
Okay, closing this then.

**Comment by barneycarroll** [comment]
Ugh. Just reappeared 😩. But on an unusual kind of brush — that may be Arcane Dimensions specific? It's a variable alpha blood decal exhibiting the issue here; I don't know what distinguishes these in technical parlance, but it's definitely the same bug.

This was after gibbing a spider in the Arcane Dimensions map [Dreamer's Demesne](https://www.quaddicted.com/reviews/ad_mfk_dreamdem+%28v1.1%29.html)

https://user-images.githubusercontent.com/83627/160863456-b63db143-1cdb-4991-9bdd-93a344385704.mp4

**Comment by Novum** [comment]
Those are completely unrelated and happen in all Quake versions

**Comment by barneycarroll** [comment]
Couldn't reproduce on QSS (couldn't record it though, the game runs on different video protocols). Should I start a new issue?

**Comment by Novum** [comment]
Yes
