### ISSUE TITLE
Regression: COM_Rand() breaking particles effects (and more ?)

### ISSUE THREAD

**Issue by vsonnier** [Novum/vkQuake#760]
Hi @Novum,

After the introduction of COM_Rand() in e6926080c0788b4c5d3efdc079b234b1694c4ea2, particles effects appears to be broken for instance rocket trails become much less dense. (and other things ?)

If you want to test a map with much more particles fireworks to see the difference, you can try [MeatJam](https://www.slipseer.com/index.php?resources/meat-jam.392/) map Carrion Star, using the provided save : shoot the 3 yellow orbs in front of you.

Turns out I found a fix making `COM_Rand()` returning a signed `int32_t` (like the original `rand()`) instead of unsigned, but I don't really see why it works !

- common.h:
```c
int32_t COM_Rand (void);
#define COM_RAND_MAX INT32_MAX
````    

- common.c:
```c
int32_t COM_Rand ()
{
	// Xorshiro64**
	... same

	return (int32_t)(result & COM_RAND_MAX);
}
````    

Using command line : `vkQuake.exe -particles 32000 -protocol 999`

Using either CI Windows 64bit builds or mines compiled with latest MSVC on a Windows10 64bit.

with [s0.zip](https://github.com/user-attachments/files/18337333/s0.zip)

**Comment by Axel-Reactor** [comment]
It's usually from conversion to floats which can't represent values over ~16.7 mio exactly. Should be simple to fix, sorry.

**Comment by vsonnier** [comment]
> Also did you try latest? I fixed a bug in the FTE code already. Or are those regular particles?

Yes, the very top. Those are regular particles , not FTE anayway. MeatJam is using Quoth, but the "missing" particles issue is visible on a standard `id1` Rocket trail also.

**Comment by Axel-Reactor** [comment]
Ok I'll fix it.

**Comment by Novum** [comment]
https://github.com/Novum/vkQuake/commit/a7f29bde4623923a897669b5ccab64026d80875a should fix this

**Comment by vsonnier** [comment]
Nope, still doesn't work, but returning `int32_t COM_Rand ()` works ! What is happening here ? 

MSYS2 binaries shows the same difference.

**Comment by andrey-budko** [comment]
Is it normal for MeatJam Carrion Star?
https://www.youtube.com/watch?v=TZCSqc2CG-0

Recorded with Ironwail, but the same with vkQuake

Sorry for the quality. This was recorded on a work computer with a GT 710, not a gaming one.

**Comment by andrey-budko** [comment]
About uint32_t COM_Rand() issue.

Look at this code
https://godbolt.org/z/zzdnYvhjz
```c++
#include <cstdio>

int main(){
    for(int rnd=0; rnd<6; rnd++){
        printf("%f %f\n",
            float((unsigned(rnd) % 6) - 3),
            float((rnd % 6) - 3)
        );
    }
}
```

Output
```
4294967296.000000 -3.000000
4294967296.000000 -2.000000
4294967296.000000 -1.000000
0.000000 0.000000
1.000000 1.000000
2.000000 2.000000
```

**Comment by vsonnier** [comment]
@andrey-budko Ah ! I think you got it we are rolling over UINT32_MAX in all cases where  `COM_Rand() - N < 0` happens.

There are many such cases in the code where the expression `COM_Rand() % D - (D/2)` seems to be used to generate random numbers in symetric intervals like -D/2 .. D/2 - 1 
So we __do__ need signed.

I'll commit the change later, unless someone beat me on it.

> Is it normal for MeatJam Carrion Star?
https://www.youtube.com/watch?v=TZCSqc2CG-0
Recorded with Ironwail, but the same with vkQuake. The same issue with host_maxfps 72.

I noticed this recently, funny thing :)

**Comment by Axel-Reactor** [comment]
The values returned are still only positive? So this is just some type inference thing because the return value is `uint32_t` instead of `int32_t`?

**Comment by andrey-budko** [comment]
COM_RandInt(min, max) probably

```c++
COM_RandInt(0, 4);
COM_RandInt(0, 7);
COM_RandInt(-3, 2);
```

instead of
```c++
COM_Rand () % 5;
COM_Rand () & 7;
COM_Rand () % 6 - 3;
```
